name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #api-level: [24,28,30]

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Install NDK
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #- name: Cache Gradle build cache
      #uses: actions/cache@v2
      #with:
        #path: ~/.gradle/caches/build-cache-7.2
        #key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        #restore-keys: |
          #${{ runner.os }}-gradle-

    #- name: Cache Gradle dependencies
      #uses: actions/cache@v2
      #with:
        #path: ~/.gradle/caches
        #key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        #restore-keys: |
          #${{ runner.os }}-gradle-

    #- name: Build debug APK
      #run: ./gradlew assembleDebug --stacktrace

    #- name: Run unit tests
      #if: "!contains(github.event.head_commit.message, '[skip tests]') && !contains(github.event.head_commit.message, '[ci skip]')"
      #uses: gradle/gradle-build-action@v1
      #with:
        #arguments: testDebugUnitTest --stacktrace
        #gradle-version: '7.2'

    #- name: Run lint checks
      #if: "!contains(github.event.head_commit.message, '[skip lint]') && !contains(github.event.head_commit.message, '[ci skip]')"
      #uses: gradle/gradle-build-action@v1
      #with:
        #arguments: lintDebug --stacktrace
        #gradle-version: '7.2'

    - name: Build with Gradle
      env:
        org.gradle.daemon: true
      run: ./gradlew build
    - name: Build debug APK
      env:
        org.gradle.daemon: true
      run: ./gradlew assemble #Debug --stacktrace #-PapiLevel=${{ matrix.api-level }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      #if: "!contains(github.event.head_commit.message, '[skip build]') && !contains(github.event.head_commit.message, '[ci skip]')"
      with:
        name: Venue-Dock
        path: app/build/outputs/apk/debug/app-debug.apk
